# Generated by Django 4.0.4 on 2022-06-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField(max_length=120)),
                ('d', models.IntegerField(max_length=120)),
                ('i', models.IntegerField(max_length=120)),
                ('j', models.IntegerField(max_length=120)),
                ('k', models.IntegerField(max_length=120)),
                ('l', models.IntegerField(max_length=120)),
                ('m', models.IntegerField(max_length=120)),
                ('n', models.IntegerField(max_length=120)),
            ],
        ),
    ]
