# Generated by Django 4.0.4 on 2022-06-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='a',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='forms',
            name='c',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='forms',
            name='e',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='forms',
            name='f',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='forms',
            name='g',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='forms',
            name='h',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='b',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='d',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='i',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='j',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='k',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='l',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='m',
            field=models.IntegerField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='forms',
            name='n',
            field=models.IntegerField(default=0, max_length=120),
        ),
    ]
