# Generated by Django 4.0.4 on 2022-06-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_forms_a_forms_c_forms_e_forms_f_forms_g_forms_h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=120)),
            ],
        ),
    ]
