# Generated by Django 4.0.4 on 2022-06-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Register',
        ),
    ]
