# Generated by Django 4.0.4 on 2022-06-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_rename_user_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
