# Generated by Django 4.0.4 on 2022-06-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=120)),
            ],
        ),
    ]
