# Generated by Django 4.0.4 on 2022-06-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_user_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
