# Generated by Django 4.0.4 on 2022-06-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='city',
            field=models.CharField(default='pu', max_length=200),
        ),
        migrations.AddField(
            model_name='forms',
            name='username',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
