# Generated by Django 4.0.4 on 2022-06-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0009_forms_city_forms_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='pred',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
