# Generated by Django 4.0.4 on 2022-07-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0010_forms_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='category',
            field=models.CharField(default='disease', max_length=100),
        ),
    ]
