# Generated by Django 4.0.4 on 2022-07-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0011_forms_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='forms2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(default=0, max_length=120)),
                ('b', models.IntegerField(default=0, max_length=120)),
                ('c', models.IntegerField(default=0, max_length=120)),
                ('d', models.IntegerField(default=0, max_length=120)),
                ('e', models.IntegerField(default=0, max_length=120)),
                ('f', models.IntegerField(default=0, max_length=120)),
                ('g', models.IntegerField(default=0, max_length=120)),
                ('h', models.IntegerField(default=0, max_length=120)),
                ('i', models.IntegerField(default=0, max_length=120)),
                ('j', models.IntegerField(default=0, max_length=120)),
                ('username', models.CharField(default='unknown', max_length=200)),
                ('city', models.CharField(default='pu', max_length=200)),
                ('pred', models.IntegerField(default=0, max_length=2)),
                ('category', models.CharField(default='disease', max_length=100)),
            ],
        ),
    ]
