# Generated by Django 4.0.4 on 2022-07-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0012_forms2'),
    ]

    operations = [
        migrations.CreateModel(
            name='forms3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(default=0, max_length=120)),
                ('b', models.IntegerField(default=0, max_length=120)),
                ('c', models.IntegerField(default=0, max_length=120)),
                ('d', models.IntegerField(default=0, max_length=120)),
                ('e', models.IntegerField(default=0, max_length=120)),
                ('f', models.IntegerField(default=0, max_length=120)),
                ('g', models.IntegerField(default=0, max_length=120)),
                ('h', models.IntegerField(default=0, max_length=120)),
                ('i', models.IntegerField(default=0, max_length=120)),
                ('j', models.IntegerField(default=0, max_length=120)),
                ('k', models.IntegerField(default=0, max_length=120)),
                ('l', models.IntegerField(default=0, max_length=120)),
                ('m', models.IntegerField(default=0, max_length=120)),
                ('n', models.IntegerField(default=0, max_length=120)),
                ('o', models.IntegerField(default=0, max_length=120)),
                ('p', models.IntegerField(default=0, max_length=120)),
                ('q', models.IntegerField(default=0, max_length=120)),
                ('r', models.IntegerField(default=0, max_length=120)),
                ('username', models.CharField(default='unknown', max_length=200)),
                ('city', models.CharField(default='pu', max_length=200)),
                ('pred', models.IntegerField(default=0, max_length=2)),
                ('category', models.CharField(default='heart', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='forms',
            name='category',
            field=models.CharField(default='heart', max_length=100),
        ),
        migrations.AlterField(
            model_name='forms2',
            name='category',
            field=models.CharField(default='liver', max_length=100),
        ),
    ]
