# Generated by Django 4.0.4 on 2022-07-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0013_forms3_alter_forms_category_alter_forms2_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms3',
            name='r',
        ),
    ]
