# Generated by Django 4.0.4 on 2022-07-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
