# Generated by Django 4.0.4 on 2022-07-01 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0016_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
