# Generated by Django 4.0.4 on 2022-07-01 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0017_forms_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='user',
        ),
        migrations.AddField(
            model_name='forms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
